### ISSUE TITLE
Any chance of an update to v2.7.6?

### ISSUE THREAD

**Issue by cablespaghetti** [burmudar/nix-cloudflare-caddy#1]
It would be great if you could update this to the latest releases and change vendorSha256 to vendorSha to fix the warning I now get on 23.11.

```
warning: `vendorSha256` is deprecated. Use `vendorHash` instead
```

Thanks, this has been really useful for me. :smile:

**Comment by burmudar** [comment]
Hey @cablespaghetti - only saw this now. I'll update it for 2.7.6 today and let you know once it has been updated :D

**Comment by burmudar** [comment]
@cablespaghetti master has been updated to v2.7.6 😄

**Comment by cablespaghetti** [comment]
Thanks so much! :smile:
